/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />

// NOTE: This file is generated by Next.js to ensure type safety.
// Do not edit this file manually.
